const bagProducts = [
    {
      id: 1, 
      title:'Bandolera DOREMI',
      price: 25000,
      category: 'bandoleras',
      description: 'Negra',
      image:"./BandoleraDOREMI.jpg",
    },
    {
      id: 2, 
      title:'Bandolera ELITE',
      price: 15000,
      category: 'bandoleras',
      description: 'Negra',
      image:"./BandoleraElite.jpg",
    },
    {
      id: 3, 
      title:'Bandolera HIT',
      price: 20000,
      category: 'bandoleras',
      description: 'Negra',
      image:"./BandoleraHit.jpg",
    },
    {
      id: 4, 
      title:'Bandolera MAILLOT',
      price: 20000,
      category: 'bandoleras',
      description: 'Negra, Violeta, Gris, Verde ',
      image:"./BandoleraMaillot.jpg",
    },
    {
      id: 5, 
      title:'Bandolera NATI',
      price: 30000,
      category: 'bandoleras',
      description: 'Negra, Violeta, Gris',
      image: "./BandoleraNati.jpg",
    },
    {
      id: 6, 
      title:'Bandolera REVERSIBLE',
      price: 30000,
      category: 'bandoleras',
      description: 'Verde',
      image:"./BandoleraReversible.jpg",
    },
    {
      id: 7, 
      title:'Bandolera RONDA',
      price: 25000,
      category: 'bandoleras',
      description: 'Negra',
      image:"./BandoleraRonda.jpg",
    },
    {
      id: 8, 
      title:'Bandolera WAXX',
      price: 18000,
      category: 'bandoleras',
      description: 'Negra',
      image: "./BandoleraWAXX.jpg",
    },
    {
      id: 9, 
      title:'Riñonera 808 7 BOLSILLOS',
      price: 18000,
      category: 'riñoneras',
      description: 'Negra',
      image:"./Riñonera808-7bolsillos.jpg",
    },
    {
      id: 10, 
      title:'Riñonera MAL',
      price: 15000,
      category: 'riñoneras',
      description: 'Negra',
      image:"./RiñoneraMal.jpg",
    },
    {
      id: 11, 
      title:'Set Matero Camuflado',
      price: 20000,
      category: 'mate',
      description: 'Verde Militar',
      image:"./SetMateroCamuflado.jpg",
    },
    {
      id: 12, 
      title:'Set Matero Negro',
      price: 20000,
      category: 'mate',
      description: 'Negro',
      image:"./SetMateroNegro.jpg",
    },
    {
      id: 13, 
      title:'Set Matero Rojo',
      price: 20000,
      category: 'mate',
      description: 'Rojo',
      image:"./SetMateroRojo.jpg",
    },
  ];

  export default bagProducts;